name: PHP Composer
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup PHP
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.2'
          
      - name: Check for composer.json changes
        id: check-changes
        if: github.event_name == 'pull_request'
        run: |
          git diff --name-only origin/${{ github.base_ref }} HEAD | grep -q "composer.json" && echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Always update in PR if composer.json changed
      - name: Update dependencies in PR
        if: github.event_name == 'pull_request' && steps.check-changes.outputs.changed == 'true'
        run: |
          composer update --prefer-dist --no-progress

      # Regular install for non-PR or when composer.json hasn't changed
      - name: Install dependencies
        if: github.event_name != 'pull_request' || steps.check-changes.outputs.changed != 'true'
        run: |
          composer install --prefer-dist --no-progress

      # Commit changes if we're in a PR and composer.json was changed
      - name: Commit and push updated lock file
        if: github.event_name == 'pull_request' && steps.check-changes.outputs.changed == 'true'
        run: |
          if git diff --exit-code composer.lock; then
            echo "No changes to composer.lock needed"
          else
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add composer.lock vendor/
            git commit -m "Update composer.lock to match composer.json changes"
            git push
          fi
