name: PHP Composer
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup PHP
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.2'
          
      - name: Check lock file status
        id: check-lock
        continue-on-error: true
        run: composer validate --strict
          
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Update dependencies if lock file is out of sync
        if: steps.check-lock.outcome == 'failure' && github.event_name == 'pull_request'
        run: |
          composer update --prefer-dist --no-progress
          
      - name: Install dependencies if lock file is valid
        if: steps.check-lock.outcome == 'success'
        run: |
          composer install --prefer-dist --no-progress
          
      - name: Commit and push updated lock file
        if: steps.check-lock.outcome == 'failure' && github.event_name == 'pull_request'
        run: |
          if git diff --exit-code composer.lock; then
            echo "No changes to composer.lock needed"
          else
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add composer.lock vendor/
            git commit -m "Update composer.lock to match composer.json changes"
            git push
          fi
